name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Validate and Build Docker App
        run: |
          docker version
          sudo rm /etc/docker/daemon.json
          sudo bash -c 'echo "{\"experimental\": true}" > /etc/docker/daemon.json'
          sudo service docker restart
          docker version -f '{{.Server.Experimental}}'

          docker app validate dot-base.dockerapp
          docker app build dot-base.dockerapp -t ghcr.io/dot-base/dot-base:latest
