name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_CLI_EXPERIMENTAL: enabled
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Validate and Build Docker App
        run: |
          docker version
          sudo rm /etc/docker/daemon.json
          sudo bash -c 'echo "{\"experimental\": true}" > /etc/docker/daemon.json'
          export OSTYPE="$(uname | tr A-Z a-z)"
          curl -fsSL --output "/tmp/docker-app-${OSTYPE}.tar.gz" "https://github.com/docker/app/releases/download/v0.8.0/docker-app-${OSTYPE}.tar.gz"
          tar xf "/tmp/docker-app-${OSTYPE}.tar.gz" -C /tmp/
          mkdir -p ~/.docker/cli-plugins && cp "/tmp/docker-app-plugin-${OSTYPE}" ~/.docker/cli-plugins/docker-app
          sudo service docker restart
          docker version

          docker app validate dot-base.dockerapp
          docker app build dot-base.dockerapp -t ghcr.io/dot-base/dot-base:latest
